services:
  backend:
    image: apnaopd-backend:latest
    container_name: backend
    ports:
      - "5000:5000"

  frontend:
    image: apnaopd-frontend:latest
    container_name: frontend
    ports:
      - "5173:5173"


#docker compose -f docker-compose-prebuild-img.yml up