#Backend docker file
# Use official Node image
FROM node:22-bullseye

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json first
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the backend code
COPY . .

# Expose port
EXPOSE 5000

# Start the server
CMD ["node", "server.js"]


# docker build -t img-opd-dbservice ../backend
# docker run -d -p 5000:5000 img-opd-dbservice:latest
# docker stop name/containerid


