#Backend docker file
# Use official Node image
FROM node:22-bullseye

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json first
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the backend code
COPY . .

# Expose port
EXPOSE 3000

# Start the server
CMD ["node", "src/server.js"]


# docker build -t img-ai-disease-predict-service ./ai-DiseasePredictService
# docker run -d -p 3000:3000 img-ai-disease-predict-service:latest
#docker stop name/containerid

